"""Add symptoms, health assessments, observations, and notes tables

Revision ID: 0ebef2ee28b2
Revises: 8cfc261b9af0
Create Date: 2026-10-05 23:55:37.410111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebef2ee28b2'
down_revision = '8cfc261b9af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptoms_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptoms_name'), ['name'], unique=True)

    op.create_table('health_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_assessments_pet_id'), ['pet_id'], unique=False)

    op.create_table('assessment_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_notes_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('assessment_symptoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('duration_value', sa.Float(), nullable=False),
    sa.Column('duration_unit', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'symptom_id', name='uq_assessment_symptom')
    )
    with op.batch_alter_table('assessment_symptoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_symptoms_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_symptoms_symptom_id'), ['symptom_id'], unique=False)

    op.create_table('health_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('appetite', sa.String(length=50), nullable=True),
    sa.Column('water_intake', sa.String(length=50), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('behaviour_change', sa.String(length=50), nullable=True),
    sa.Column('sleep_change', sa.String(length=50), nullable=True),
    sa.Column('stool_change', sa.String(length=50), nullable=True),
    sa.Column('urine_change', sa.String(length=50), nullable=True),
    sa.Column('breathing_change', sa.String(length=50), nullable=True),
    sa.Column('pain_observed', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_observations_assessment_id'), ['assessment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_observations_assessment_id'))

    op.drop_table('health_observations')
    with op.batch_alter_table('assessment_symptoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_symptoms_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_symptoms_assessment_id'))

    op.drop_table('assessment_symptoms')
    with op.batch_alter_table('assessment_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_notes_assessment_id'))

    op.drop_table('assessment_notes')
    with op.batch_alter_table('health_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_assessments_pet_id'))

    op.drop_table('health_assessments')
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptoms_name'))
        batch_op.drop_index(batch_op.f('ix_symptoms_category'))

    op.drop_table('symptoms')
    # ### end Alembic commands ###
