"""Add Step 3: follow_up_questions, follow_up_question_options, assessment_answers tables

Revision ID: 37f1877f260e
Revises: 0ebef2ee28b2
Create Date: 2026-10-08 19:56:46.758135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f1877f260e'
down_revision = '0ebef2ee28b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('symptom_id', sa.String(length=36), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('min_age_months', sa.Integer(), nullable=True),
    sa.Column('max_age_months', sa.Integer(), nullable=True),
    sa.Column('is_emergency_related', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_questions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_questions_symptom_id'), ['symptom_id'], unique=False)

    op.create_table('follow_up_question_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('option_value', sa.String(length=100), nullable=False),
    sa.Column('severity_weight', sa.Float(), nullable=True),
    sa.Column('emergency_flag', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['follow_up_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('assessment_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_id', sa.String(length=36), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('triggered_emergency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['follow_up_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['follow_up_question_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_assessment_answer')
    )
    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_answers_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_answers_assessment_id'))

    op.drop_table('assessment_answers')
    with op.batch_alter_table('follow_up_question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_question_options_question_id'))

    op.drop_table('follow_up_question_options')
    with op.batch_alter_table('follow_up_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_questions_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_questions_category'))

    op.drop_table('follow_up_questions')
    # ### end Alembic commands ###
