"""add Step 5 assessment_images and image_observations tables

Revision ID: 59cc494aca3f
Revises: f13704143945
Create Date: 2026-10-08 20:49:28.587585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cc494aca3f'
down_revision = 'f13704143945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('quality_gate', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_images_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_images_pet_id'), ['pet_id'], unique=False)

    op.create_table('image_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_image_id', sa.String(length=36), nullable=False),
    sa.Column('observation_type', sa.String(length=50), nullable=False),
    sa.Column('observation_label', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_image_id'], ['assessment_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_observations_assessment_image_id'), ['assessment_image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_observations_assessment_image_id'))

    op.drop_table('image_observations')
    with op.batch_alter_table('assessment_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_images_pet_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_images_assessment_id'))

    op.drop_table('assessment_images')
    # ### end Alembic commands ###
