"""add Step 4 assessment_risk_analyses table

Revision ID: f13704143945
Revises: 37f1877f260e
Create Date: 2026-10-08 20:27:05.207542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13704143945'
down_revision = '37f1877f260e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_risk_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('key_factors', sa.JSON(), nullable=False),
    sa.Column('factor_breakdown', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_risk_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_risk_analyses_assessment_id'), ['assessment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_risk_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_risk_analyses_assessment_id'))

    op.drop_table('assessment_risk_analyses')
    # ### end Alembic commands ###
