"""add Step 6 assessment_reports table

Revision ID: fddebcfeb1c5
Revises: 59cc494aca3f
Create Date: 2026-10-08 21:09:41.408561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddebcfeb1c5'
down_revision = '59cc494aca3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('report_status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['health_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'report_version', name='uq_assessment_report_version')
    )
    with op.batch_alter_table('assessment_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_reports_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_reports_assessment_id'))

    op.drop_table('assessment_reports')
    # ### end Alembic commands ###
